name: "Build"

on:
  push:
    branches:
      - src
      - 'pages/*'
  schedule:
  - cron: 30 2,8,14,20 * * *

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    env:
      CI: true
      PATREON_BEARER: ${{ secrets.PATREON_BARER }}
      PATREON_CAMPAIGN: ${{ secrets.PATREON_CAMPAIGN }}
      LB_TOKEN: ${{ secrets.LB_TOKEN }}
    steps:
    - name: Post Starting
      run: |
        curl -X POST -H "Content-Type: application/json" -d '{"i":"${{secrets.MK_I}}", "text":"[🆕 Build Starting (${{github.event_name}})](https://github.com/joinmisskey/joinmisskey.github.io/commit/${{ github.sha }}/checks)"}' https://c2.a9z.dev/api/notes/create
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Vals
      run: |
        echo "SHA: $GITHUB_SHA"
        echo "REF: $GITHUB_REF"
        echo "ACTION: $GITHUB_ACTION"
        echo "COMMIT MSG: ${{ github.event.head_commit.message }}"
    - name: Git init
      run: |
        git init
        git remote add origin https://luckybeast:${{ secrets.LB_TOKEN }}@github.com/joinmisskey/joinmisskey.github.io
        git config --global user.name "luckybeast"
        git config --global user.email "remu.teshigawara@gmail.com"
        git fetch --depth 1
        git checkout src
        ./.github/workflows/git-worktrees.sh
    - name: Copy Pages
      run: "./.github/workflows/copy-pages.sh"
    - name: Yarn Install
      run: yarn install
    - name: Build Pages
      if: "github.event_name == 'schedule' || (!contains(github.event.head_commit.message, 'wo:build') && !contains(github.event.head_commit.message, 'w:build:assets') && !contains(github.event.head_commit.message, 'w:build:all'))"
      run: gulp pages
    - name: Build Assets & Pages
      if: "github.event_name != 'schedule' && contains(github.event.head_commit.message, 'w:build:assets') && !contains(github.event.head_commit.message, 'w:build:all')"
      run: gulp
    - name: Build All
      if: "github.event_name != 'schedule' && !contains(github.event.head_commit.message, 'w:build:assets') && contains(github.event.head_commit.message, 'w:build:all')"
      run: gulp all
    - name: Git Push Results
      if: "github.event_name == 'schedule' || !contains(github.event.head_commit.message, 'wo:push')"
      run: "./.github/workflows/git-push-results.sh"
    - name: Post Success
      if: success()
      run: |
        curl -X POST -H "Content-Type: application/json" -d '{"i":"${{secrets.MK_I}}", "text":"[☑ Build Successed](https://github.com/joinmisskey/joinmisskey.github.io/commit/${{ github.sha }}/checks)"}' https://c2.a9z.dev/api/notes/create
    - name: Post Failure
      if: failure()
      run: |
        curl -X POST -H "Content-Type: application/json" -d '{"i":"${{secrets.MK_I}}", "text":"[🚨 **Build Failure** 🚨](https://github.com/joinmisskey/joinmisskey.github.io/commit/${{ github.sha }}/checks)"}' https://c2.a9z.dev/api/notes/create
    - name: Post Cancelled
      if: cancelled()
      run: |
        curl -X POST -H "Content-Type: application/json" -d '{"i":"${{secrets.MK_I}}", "text":"[✋ Build Cancelled](https://github.com/joinmisskey/joinmisskey.github.io/commit/${{ github.sha }}/checks)"}' https://c2.a9z.dev/api/notes/create
