name: "Build"

on:
  push:
    branches:
      - src
      - 'pages/*'
#  schedule:
#  - cron: 30 2,14 * * *

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [13.x]
    env:
      CI: true
      PATREON_BEARER: ${{ secrets.PATREON_BARER }}
      PATREON_CAMPAIGN: ${{ secrets.PATREON_CAMPAIGN }}
    steps:
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Vals
      run: |
        echo "SHA: $GITHUB_SHA"
        echo "REF: $GITHUB_REF"
        echo "ACTION: $GITHUB_ACTION"
        echo "COMMIT MSG: ${{ github.event.head_commit.message }}"
    - name: Git init
      run: |
        git init
        git remote add origin https://luckybeast:${{ secrets.LB_TOKEN }}@github.com/joinmisskey/joinmisskey.github.io
        git config --global user.name "luckybeast"
        git config --global user.email "remu.teshigawara@gmail.com"
        git fetch
        git checkout src
        ./.github/workflows/git-worktrees.sh
    - name: Copy Pages
      run: "./.github/workflows/copy-pages.sh"
    - name: Yarn Install
      run: yarn install
    - name: Build Pages
      if: "github.event_name == 'schedule' || (!contains(github.event.head_commit.message, 'wo:build') && !contains(github.event.head_commit.message, 'w:build:assets') && !contains(github.event.head_commit.message, 'w:build:all'))"
      run: gulp pages
    - name: Build Assets & Pages
      if: "github.event_name != 'schedule' && contains(github.event.head_commit.message, 'w:build:assets') && !contains(github.event.head_commit.message, 'w:build:all')"
      run: gulp
    - name: Build All
      if: "github.event_name != 'schedule' && !contains(github.event.head_commit.message, 'w:build:assets') && contains(github.event.head_commit.message, 'w:build:all')"
      run: gulp all
    - name: Git Push Results
      run: "./.github/workflows/git-push-results.sh"
