name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [13.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: BUILD
      run: |
        git config --global user.name "luckybeast"
        git config --global user.email "remu.teshigawara@gmail.com"
        git remote set-url origin https://luckybeast:${{ secrets.GITHUB_TOKEN }}@github.com/joinmisskey/joinmisskey.github.io
        git checkout src
        git worktree add docs master
        git worktree add pages/ja pages/ja
        git worktree add pages/en pages/en
        git worktree add pages/fr pages/fr
        cd pages/en
        git pull origin pages/en
        git pull origin pages/ja
        git push
        cd ../fr
        git pull origin pages/fr
        git pull origin pages/ja
        git push
        cd ../..
        yarn install
        gulp pages
      # ./push-ja.sh
      env:
        CI: true
        PATREON_BARER: ${{ secrets.PATREON_BARER }}
        PATREON_CAMPAIGN: ${{ secrets.PATREON_CAMPAIGN }}
